#########################
## Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: html
  # Output file instead of logging results
#  output-file: 'linters/sass-lint.html'
# File Options
files:
#  include: 'source/stylesheets/**/*.s+(a|c)ss'
#  ignore:
#    - 'source/stylesheets/foundations/**/*.*'
# Rule Configuration
rules:
#  extends-before-mixins: 2
#  extends-before-declarations: 2
